# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/Users/lucius/Documents/Drive/Builds/clevercheck.io/mcc-mnc_scraper/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/lucius/.cache/prisma-python/binaries/5.17.0/393aa359c9ad4a4bb28630fb5613f9c281cde053/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    company: 'actions.CompanyActions[models.Company]'
    plan: 'actions.PlanActions[models.Plan]'
    cloudsettings: 'actions.CloudSettingsActions[models.CloudSettings]'
    user: 'actions.UserActions[models.User]'
    device: 'actions.DeviceActions[models.Device]'
    testresult: 'actions.TestResultActions[models.TestResult]'
    certificate: 'actions.CertificateActions[models.Certificate]'
    session: 'actions.SessionActions[models.Session]'
    cloudsession: 'actions.CloudSessionActions[models.CloudSession]'
    transaction: 'actions.TransactionActions[models.Transaction]'
    mobilenetworks: 'actions.MobileNetworksActions[models.MobileNetworks]'

    __slots__ = (
        'company',
        'plan',
        'cloudsettings',
        'user',
        'device',
        'testresult',
        'certificate',
        'session',
        'cloudsession',
        'transaction',
        'mobilenetworks',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.company = actions.CompanyActions[models.Company](self, models.Company)
        self.plan = actions.PlanActions[models.Plan](self, models.Plan)
        self.cloudsettings = actions.CloudSettingsActions[models.CloudSettings](self, models.CloudSettings)
        self.user = actions.UserActions[models.User](self, models.User)
        self.device = actions.DeviceActions[models.Device](self, models.Device)
        self.testresult = actions.TestResultActions[models.TestResult](self, models.TestResult)
        self.certificate = actions.CertificateActions[models.Certificate](self, models.Certificate)
        self.session = actions.SessionActions[models.Session](self, models.Session)
        self.cloudsession = actions.CloudSessionActions[models.CloudSession](self, models.CloudSession)
        self.transaction = actions.TransactionActions[models.Transaction](self, models.Transaction)
        self.mobilenetworks = actions.MobileNetworksActions[models.MobileNetworks](self, models.MobileNetworks)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/Users/lucius/Documents/Drive/Builds/clevercheck.io/mcc-mnc_scraper/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    company: 'CompanyBatchActions'
    plan: 'PlanBatchActions'
    cloudsettings: 'CloudSettingsBatchActions'
    user: 'UserBatchActions'
    device: 'DeviceBatchActions'
    testresult: 'TestResultBatchActions'
    certificate: 'CertificateBatchActions'
    session: 'SessionBatchActions'
    cloudsession: 'CloudSessionBatchActions'
    transaction: 'TransactionBatchActions'
    mobilenetworks: 'MobileNetworksBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.company = CompanyBatchActions(self)
        self.plan = PlanBatchActions(self)
        self.cloudsettings = CloudSettingsBatchActions(self)
        self.user = UserBatchActions(self)
        self.device = DeviceBatchActions(self)
        self.testresult = TestResultBatchActions(self)
        self.certificate = CertificateBatchActions(self)
        self.session = SessionBatchActions(self)
        self.cloudsession = CloudSessionBatchActions(self)
        self.transaction = TransactionBatchActions(self)
        self.mobilenetworks = MobileNetworksBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CompanyBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CompanyCreateInput,
        include: Optional[types.CompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Company,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CompanyCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Company,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CompanyWhereUniqueInput,
        include: Optional[types.CompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Company,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CompanyUpdateInput,
        where: types.CompanyWhereUniqueInput,
        include: Optional[types.CompanyInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Company,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CompanyWhereUniqueInput,
        data: types.CompanyUpsertInput,
        include: Optional[types.CompanyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Company,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CompanyUpdateManyMutationInput,
        where: types.CompanyWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Company,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CompanyWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Company,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PlanBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PlanCreateInput,
        include: Optional[types.PlanInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Plan,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PlanCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Plan,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PlanWhereUniqueInput,
        include: Optional[types.PlanInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Plan,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PlanUpdateInput,
        where: types.PlanWhereUniqueInput,
        include: Optional[types.PlanInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Plan,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PlanWhereUniqueInput,
        data: types.PlanUpsertInput,
        include: Optional[types.PlanInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Plan,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PlanUpdateManyMutationInput,
        where: types.PlanWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Plan,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PlanWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Plan,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CloudSettingsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CloudSettingsCreateInput,
        include: Optional[types.CloudSettingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CloudSettings,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CloudSettingsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CloudSettings,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CloudSettingsWhereUniqueInput,
        include: Optional[types.CloudSettingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CloudSettings,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CloudSettingsUpdateInput,
        where: types.CloudSettingsWhereUniqueInput,
        include: Optional[types.CloudSettingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CloudSettings,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CloudSettingsWhereUniqueInput,
        data: types.CloudSettingsUpsertInput,
        include: Optional[types.CloudSettingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CloudSettings,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CloudSettingsUpdateManyMutationInput,
        where: types.CloudSettingsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CloudSettings,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CloudSettingsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CloudSettings,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class DeviceBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.DeviceCreateInput,
        include: Optional[types.DeviceInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Device,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.DeviceCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Device,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.DeviceWhereUniqueInput,
        include: Optional[types.DeviceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Device,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.DeviceUpdateInput,
        where: types.DeviceWhereUniqueInput,
        include: Optional[types.DeviceInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Device,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.DeviceWhereUniqueInput,
        data: types.DeviceUpsertInput,
        include: Optional[types.DeviceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Device,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.DeviceUpdateManyMutationInput,
        where: types.DeviceWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Device,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.DeviceWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Device,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TestResultBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TestResultCreateInput,
        include: Optional[types.TestResultInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.TestResult,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TestResultCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.TestResult,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TestResultWhereUniqueInput,
        include: Optional[types.TestResultInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.TestResult,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TestResultUpdateInput,
        where: types.TestResultWhereUniqueInput,
        include: Optional[types.TestResultInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.TestResult,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TestResultWhereUniqueInput,
        data: types.TestResultUpsertInput,
        include: Optional[types.TestResultInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.TestResult,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TestResultUpdateManyMutationInput,
        where: types.TestResultWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.TestResult,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TestResultWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.TestResult,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CertificateBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CertificateCreateInput,
        include: Optional[types.CertificateInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Certificate,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CertificateCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Certificate,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CertificateWhereUniqueInput,
        include: Optional[types.CertificateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Certificate,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CertificateUpdateInput,
        where: types.CertificateWhereUniqueInput,
        include: Optional[types.CertificateInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Certificate,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CertificateWhereUniqueInput,
        data: types.CertificateUpsertInput,
        include: Optional[types.CertificateInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Certificate,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CertificateUpdateManyMutationInput,
        where: types.CertificateWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Certificate,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CertificateWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Certificate,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SessionCreateInput,
        include: Optional[types.SessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Session,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Session,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SessionWhereUniqueInput,
        include: Optional[types.SessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Session,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SessionUpdateInput,
        where: types.SessionWhereUniqueInput,
        include: Optional[types.SessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Session,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SessionWhereUniqueInput,
        data: types.SessionUpsertInput,
        include: Optional[types.SessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Session,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SessionUpdateManyMutationInput,
        where: types.SessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Session,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Session,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class CloudSessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.CloudSessionCreateInput,
        include: Optional[types.CloudSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.CloudSession,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.CloudSessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.CloudSession,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.CloudSessionWhereUniqueInput,
        include: Optional[types.CloudSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.CloudSession,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.CloudSessionUpdateInput,
        where: types.CloudSessionWhereUniqueInput,
        include: Optional[types.CloudSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.CloudSession,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.CloudSessionWhereUniqueInput,
        data: types.CloudSessionUpsertInput,
        include: Optional[types.CloudSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.CloudSession,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.CloudSessionUpdateManyMutationInput,
        where: types.CloudSessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.CloudSession,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.CloudSessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.CloudSession,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TransactionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TransactionCreateInput,
        include: Optional[types.TransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Transaction,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TransactionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Transaction,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TransactionWhereUniqueInput,
        include: Optional[types.TransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Transaction,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TransactionUpdateInput,
        where: types.TransactionWhereUniqueInput,
        include: Optional[types.TransactionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Transaction,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TransactionWhereUniqueInput,
        data: types.TransactionUpsertInput,
        include: Optional[types.TransactionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Transaction,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TransactionUpdateManyMutationInput,
        where: types.TransactionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Transaction,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TransactionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Transaction,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MobileNetworksBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MobileNetworksCreateInput,
        include: Optional[types.MobileNetworksInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.MobileNetworks,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MobileNetworksCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.MobileNetworks,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MobileNetworksWhereUniqueInput,
        include: Optional[types.MobileNetworksInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.MobileNetworks,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MobileNetworksUpdateInput,
        where: types.MobileNetworksWhereUniqueInput,
        include: Optional[types.MobileNetworksInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.MobileNetworks,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MobileNetworksWhereUniqueInput,
        data: types.MobileNetworksUpsertInput,
        include: Optional[types.MobileNetworksInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.MobileNetworks,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MobileNetworksUpdateManyMutationInput,
        where: types.MobileNetworksWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.MobileNetworks,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MobileNetworksWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.MobileNetworks,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma