# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class TransactionType(StrEnum):
    CREDIT = 'CREDIT'
    DEBIT = 'DEBIT'

class TransactionReason(StrEnum):
    PURCHASE = 'PURCHASE'
    DEVICE_TEST = 'DEVICE_TEST'
    REFUND = 'REFUND'
    ADJUSTMENT = 'ADJUSTMENT'
    PROMOTION = 'PROMOTION'
    TRANSFER = 'TRANSFER'
    UNKNOWN = 'UNKNOWN'

class TransactionStatus(StrEnum):
    PENDING = 'PENDING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    REVERSED = 'REVERSED'

class UserRole(StrEnum):
    ULTRA = 'ULTRA'
    SUPPORT = 'SUPPORT'
    ADMIN = 'ADMIN'
    TESTER = 'TESTER'
    TECHNICIAN = 'TECHNICIAN'

