from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Company',
    'Plan',
    'CloudSettings',
    'User',
    'Device',
    'TestResult',
    'Certificate',
    'Session',
    'CloudSession',
    'Transaction',
    'MobileNetworks',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Company': {
        'cloudSettings': 'CloudSettings',
        'devices': 'Device',
        'plan': 'Plan',
        'transactions': 'Transaction',
        'users': 'User',
    },
    'Plan': {
        'company': 'Company',
    },
    'CloudSettings': {
        'company': 'Company',
    },
    'User': {
        'cloudSessions': 'CloudSession',
        'sessions': 'Session',
        'testResults': 'TestResult',
        'transactions': 'Transaction',
        'company': 'Company',
    },
    'Device': {
        'company': 'Company',
        'testResults': 'TestResult',
    },
    'TestResult': {
        'certificate': 'Certificate',
        'device': 'Device',
        'tester': 'User',
    },
    'Certificate': {
        'testResult': 'TestResult',
    },
    'Session': {
        'user': 'User',
    },
    'CloudSession': {
        'user': 'User',
    },
    'Transaction': {
        'company': 'Company',
        'user': 'User',
    },
    'MobileNetworks': {
    },
}

# fmt: on